### ISSUE TITLE
Respecting XDG_CONFIG_HOME?

### ISSUE THREAD

**Issue by seqizz** [orhun/rustypaste-cli#1]
Hi,

I've now switching from shell function to this tool (thanks btw) and realized config file location is directly under $HOME. Would you consider switching to place/search under .config folder by default?

**Comment by orhun** [comment]
Hello!
I don't think I will do it since the config file contains secrets such as `auth_token`. From my experience, it is not the best choice to put such files under `config/`. (e.g. `~/.cargo/credentials`, `~/.aws/config` and so on)
