### ISSUE TITLE
Support standard input

### ISSUE THREAD

**Issue by inglor** [orhun/rustypaste-cli#19]
It would be nice to have rustypaste-cli to support inpur from std input. Then once can do 
```
rpaste < xclip -o
```

The workaround I currently do is create a tmp file and rpaste that which is not optimal.

**Comment by orhun** [comment]
This is supported: https://github.com/orhun/rustypaste-cli#upload-from-stdin

Can you try using `-`?

**Comment by inglor** [comment]
Aha! cool thanks for this quick answer.
