### ISSUE TITLE
Add progress bar for large files

### ISSUE THREAD

**Issue by svenstaro** [orhun/rustypaste-cli#6]
Uploading large files takes quite some time sometimes and it'd be great to have some kind of progress indicator. I think it would add a lot of usability while not being too hard to implement. Besides, there are some really pretty progress bars around!

**Comment by orhun** [comment]
Hey, thanks for the suggestion! 🐻

I added a progress indicator in 1fe97a08431a99b63dbef95b6b3f02e2c7a7295e

![rec_20221231T165438](https://user-images.githubusercontent.com/24392180/210139218-7c309398-1e4c-4323-ace7-ba30baf3c9d2.gif)

**Comment by orhun** [comment]
Released this feature via `0.3.0` 🚀

**Comment by svenstaro** [comment]
Super nice 👍
