### ISSUE TITLE
auto-merge dependabot PRs (mergify)

### ISSUE THREAD

**Issue by tessus** [orhun/rustypaste-cli#95]
Just a reminder and for tracking purposes.

**Comment by tessus** [comment]
As an additional note: the CI workflow should only test rust stable. Otherwise dependabot PRs are not merged because of bugs or issues in rust nightly.

It's not a problem to create a 2nd workflow that tests beta and nightly which is just informative and not authorative in regards to mergability.

**Comment by orhun** [comment]
Yup, makes sense. Can you send a PR to split them?

**Comment by tessus** [comment]
will do

**Comment by tessus** [comment]
I can't setup the automerge, since the branch protection must be setup in the repo settings.
Only the stable CI should be taken into consideration for the auto-merge.

But I think the PRs should be merged and then it's time for a new release.

**Comment by orhun** [comment]
Mergify is already set up:

![image](https://github.com/orhun/rustypaste-cli/assets/24392180/28beb20d-a7ed-4bdb-aa6a-6d439a7ebad9)

Not sure why the auto merge for Dependabot is not working. I have the exact same setup on other repos.

**Comment by tessus** [comment]
Unfortunately I can't help here. Even if I had access to the repo's settings, I wouldn't be able to fix it either. You have set it up before, so I am sure you have done everything by the book. I suspect you might have to open a ticket with them.

**Comment by orhun** [comment]
Yeah, I think so too. Doing that is more annoying that merging everything manually so I will close this for now lol

> P.S.: Thanks for the new release. ❤️

Thanks for your contributions!

**Comment by tessus** [comment]
> Yeah, I think so too. Doing that is more annoying that merging everything manually so I will close this for now lol

Haha, true. Although I would also like to know why it's not working. Hmm, maybe I can set it up on my cloned repo and open a ticket. I'll play around a bit later.

> Thanks for your contributions!

Thank you for your reviews. I learn a lot about Rust.
